version: '3.8'

services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - app_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"

  blog:
    image: blog:v1
    build:
      context: ./swarm_microservices.blog
      dockerfile: Dockerfile
    ports:
      - "5051:80"
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.3"
          memory: "100M"
      restart_policy:
        condition: any
    depends_on:
      - consul

  auth:
    image: auth:v1
    build:
      context: ./swarm_microservices.auth
      dockerfile: Dockerfile
    ports:
      - "5140:80"
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.3"
          memory: "100M"
      restart_policy:
        condition: any 
    depends_on:
      - consul

  gateway:
    image: gateway:v1
    build:
      context: ./swarm_microservices.gateway
      dockerfile: Dockerfile
    ports:
      - "5264:80"
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.3"
          memory: "100M"
      restart_policy:
        condition: any
    depends_on:
      - consul

networks:
  app_network:
    driver: overlay